import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import {Montserrat} from 'next/font/google';
import {cn} from "@/utils/utils";
import "./globals.css";

const montserrat = Montserrat({
    subsets: ['latin'],
    display: 'swap',
});

export const metadata = {
    title: "Euro finantare",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className="antialiased">
        <div
            className={cn(montserrat.className, "relative flex flex-col h-full min-h-screen w-full min-w-screen items-center text-[#212121]")}>
            <Header/>
            <main className="flex flex-1 flex-col items-center w-full h-full">
                {children}
            </main>
            <Footer/>
        </div>
        </body>
        </html>
    );
}
